### ISSUE TITLE
`undefined-ago` in state change label since NodeBB v3.6.6

### ISSUE THREAD

**Issue by nebulade** [NodeBB/nodebb-plugin-question-and-answer#103]
Changing the state of a thread will result in a broken event label since NodeBB update to 3.6.6:
```
[[undefined-ago, username, 22 minutes ago]]
```
![image](https://github.com/NodeBB/nodebb-plugin-question-and-answer/assets/646768/59abcf3c-d278-40b9-9e5b-ac67e428fbd8)

There are no errors shown in the browser console. Rebuilding NodeBB and also re-adding the plugin results in the same behavior.

**Comment by barisusakli** [comment]
@nebulade what version of the plugin are you using?

**Comment by barisusakli** [comment]
Testing with nodebb 3.6.6 and plugin version 1.2.7 seems to work.

![image](https://github.com/NodeBB/nodebb-plugin-question-and-answer/assets/2583394/4506876f-31b3-4441-b587-b397cec9bfd0)

**Comment by barisusakli** [comment]
Hmm weird, the suggested version in the acp comes from the url `https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-question-and-answer&version=3.6.6` so it should display 1.2.7.
