### ISSUE TITLE
/unsolved page does not work with infinite scroll

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-question-and-answer#11]
load /unsolved scroll down

**Comment by psychobunny** [comment]
`/unsolved page does work`

it does work? well that's good then, #notabug :trollface:

**Comment by barisusakli** [comment]
:trollface:

**Comment by wayneworkman** [comment]
Hello from forums.fogproject.org, we are a user of nodeBB and this plugin.

We are experiencing the same issue. The 'Unsovled' listing only shows a limited amount of results, I cannot infinitely scroll down or go to the next 'page' to find older unsolved threads.

Thanks,
Wayne

**Comment by psychobunny** [comment]
already fixed here: https://github.com/NodeBB/nodebb-plugin-question-and-answer/pull/33

I published another patch just in case the current version on npm wasn't up to date
