### ISSUE TITLE
Cannot mark topic as solved or switch topic type

### ISSUE THREAD

**Issue by hoghweed** [NodeBB/nodebb-plugin-question-and-answer#16]
I've updated to source distribution of NodeBB,
after that problems are: 

1. When entering in a topic , solved or unsolved, the **SOLVED or UNSOLVED badge** not appear, in the right side latest topics column Q&A topics are shown with own badge instead
2. **Even if the SOLVED or UNSOLVED badge not appear**, if I try to mark as solved **nothing happens and no log messages are written**

Any idea?
Thanks in advance

**Comment by psychobunny** [comment]
You're on the latest master? It works for us on our community which is running the latest: https://community.nodebb.org/topic/6898/test-question/2

If not, let me know what version of NodeBB you're running?

**Comment by hoghweed** [comment]
I'm on the latest master. The la pull I made yesterday.
The strange is that no error messages or similar is on the log.
Any suggestions?

**Comment by julianlam** [comment]
Ensure you're using latest version of plugin. This should be fixed already.
