### ISSUE TITLE
Marking a specific post as an answer

### ISSUE THREAD

**Issue by whittssg** [NodeBB/nodebb-plugin-question-and-answer#18]
Did you make any progress in marking a particular post as the answer?

Thanks

**Comment by lainfox** [comment]
+1

**Comment by sorvani** [comment]
I most definitely want this feature added.

Additionally, once a post is marked as the answer, clicking on the *answered* notice should take you to the post.

**Comment by amarinelli** [comment]
I have noticed that there is a commit 1fa5bdf1cea982abaf0cb6fb564c5461d5a33266 addressing this request and the option to **mark this post as the correct answer** is visible in the overflow menu of topic replies in my forum....but it doesn't seem to do anything.  Thoughts?

**Comment by believer** [comment]
I'm running 0.0.17 and I can't even see the option for marking a post as the correct answer. Would love to have this feature! 😄

**Comment by amarinelli** [comment]
@believer: I have it in overflow menu of a topic reply.

Also running `0.0.17`

![image](https://cloud.githubusercontent.com/assets/4150021/15304046/189b3f94-1b89-11e6-9940-d56646c482a4.png)

**Comment by davecotter** [comment]
i can mark my OWN post as correct, but can not mark any one ELSE's post!  why is this not fixed after several years?  pleeeeeeeease fix this!

**Comment by davecotter** [comment]
okay,  i can't even mark my OWN post as "correct answer" (at least not on this forum, perhaps because i'm new?)  huh.
<img width="212" alt="screen shot 2017-08-10 at 9 05 37 am" src="https://user-images.githubusercontent.com/259854/29180051-5cada4f8-7dab-11e7-9689-f7686179cfdc.png">

**Comment by d0dge** [comment]
Expanding on this request slightly, would it be possible to make it COMPULSORY to mark a post as the answer before you can mark it as solved?

Currently people can mark the question as solved, but it's not necessarily obvious which post is the correct answer.  I think it would be good to force the marking of an answer as the correct one before it can be marked as solved.

**Comment by davecotter** [comment]
wow i guess i thought this bug would have already been fixed, a year later

**Comment by barisusakli** [comment]
This should be working, let us know if it is not.
https://community.nodebb.org/topic/13570/how-does-q-a-work
