### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by Benderwan** [NodeBB/nodebb-plugin-question-and-answer#22]
Re-hey :grin: 

Would be great if you added the support to create PR with language files as does https://github.com/Schamper/nodebb-plugin-poll

Thanks !

**Comment by sohrabafard** [comment]
yes it's very good idea,
I'm trying to translate plugin in my forum, but when you publish an upgrade, translated `js` gone!

so if you add a language file, each forum admin can translate his or her plugin!

**Comment by exomarty** [comment]
+1

**Comment by emxjay** [comment]
+1

**Comment by pejuaxel** [comment]
+1

**Comment by Jey-Cee** [comment]
+1
