### ISSUE TITLE
Cannot create normal topics if QA is the default

### ISSUE THREAD

**Issue by ollipuu** [NodeBB/nodebb-plugin-question-and-answer#25]
I wrote this as a comment to a related closed issue #12, but I guess it gets buried in there. That issue is marked as fixed, but we still have issues creating normal topics if QA is the default type.

In main.js#34 starts a condition to check, whether to set the QA as a default type.

``` javascript
if (
        config['question-and-answer'].forceQuestions === 'on' ||
        (
                config['question-and-answer'].makeDefault === 'on' &&
                (config['question-and-answer'].defaultCid === "0" || parseInt(config['question-and-answer'].defaultCid, 10) === data.composerData.cid)
        )
) {
        $('.composer-submit').attr('data-action', 'post').html('<i class="fa fa-fw fa-question-circle"></i> Ask as Question</a>');
        $(window).off('action:composer.topics.post').one('action:composer.topics.post', function(ev, data) {
                callToggleQuestion(data.data.tid);
        });
}
```

If QA is the default, callToggleQuestion is called after the topic is created. Function callToggleQuestion calls toggleQuestionStatus in library.js, where topics.getTopicField triggers a callback with parameter isQuestion. Because the topic was just created, the value of isQuestion is null. The next comparison

``` javascript
isQuestion = parseInt(isQuestion, 10) === 1;
```

sets the value of isQuestion to 0 and after that the code toggles the value to 1 so that when a new topic is created (if the default type is QA and no matter what the value of the dropdown is), the topic type will be a question.

Plugin version: 0.0.16
NodeBB version: 0.9.3 (cloned about a month ago)
Theme: Own theme, inherited from Vanilla.

**Comment by psychobunny** [comment]
Should be good in latest version :)
