### ISSUE TITLE
/unsolved route shows both solved and unsolved topics

### ISSUE THREAD

**Issue by amarinelli** [NodeBB/nodebb-plugin-question-and-answer#29]
/solved route only shows solved topics.

**Comment by AmrEldib** [comment]
This is for version 0.0.17 on NodeBB v1.0.2

**Comment by pichalite** [comment]
cannot reproduce on NodeBB v1.1.0 using 0.0.18

**Comment by pichalite** [comment]
aah I see... happens when infinite loader kicks in and loads more topics.
