### ISSUE TITLE
Cannot Make a New Question At Submission Time

### ISSUE THREAD

**Issue by scottalanmiller** [NodeBB/nodebb-plugin-question-and-answer#34]
https://mangolassi.it/topic/10056/cannot-mark-a-topic-as-a-question/

When someone makes a new thread, the drop down to "Mark as a Question" is missing from the Submit button.  This is a very recent change that we have noticed.  This was working until maybe the NodeBB update to 1.1.0.  We can still use Topic Tools to make it as a question, but the OP can't do it when creating the thread.  Plugin was updated today to test, no change.  Plugin is on 0.1.0.

**Comment by pichalite** [comment]
try latest version

**Comment by psychobunny** [comment]
This one broke and unbroke a few times, but it should be fixed in the latest version
