### ISSUE TITLE
Change the default behaviour for new topics to be a Q&A topic

### ISSUE THREAD

**Issue by nullmu0** [NodeBB/nodebb-plugin-question-and-answer#36]
Change the default behaviour for new topics to be a Q&A topic
how multi select ?

**Comment by amarinelli** [comment]
I agree with @junjun16818, in the _Q&A General Plugin Settings_, if you check the option `Change the default behaviour for new topics to be a Q&A topic` then when composing a new topic, you don't get the option to switch back to a regular topic.

![image](https://cloud.githubusercontent.com/assets/4150021/17862360/e47f4de6-6862-11e6-8349-07f582b4c636.png)

NodeBB **v1.0.3**
nodebb-plugin-question-and-answer **v0.1.2**

**Comment by ET-Bent** [comment]
@amarinelli is that picture a mockup or is this really a thing?

**Comment by amarinelli** [comment]
@ET-Bent, that was the real thing.  We just updated core software (to _v1.1.2_ and Q&A to _v0.1.3_) so I will have to check on this again.

**Comment by psychobunny** [comment]
Cleaning up old issues; this is an option in the latest version
