### ISSUE TITLE
I think there are some problems on the authority and reward.

### ISSUE THREAD

**Issue by dofy** [NodeBB/nodebb-plugin-question-and-answer#39]
1. the topic author only can make himself post as correct answer.
2. the other users can see the `make this post as correct answer` button, but dosn't work.

I think these problems maybe like this:
1. only admin and the topic author can make post as correct answer.
2. the others can not see the button

btw.
when the `solved` question is reset to `unsolved`, the reward should be recovered.

**Comment by barisusakli** [comment]
everything other than the reward bit is working
