### ISSUE TITLE
"Ask as question" dropdown doesn't change the submit button on nodebb 1.4.0

### ISSUE THREAD

**Issue by joolswills** [NodeBB/nodebb-plugin-question-and-answer#43]
nodebb 1.4.0 9d120ee86cfe2a55efcd3982cc3e8fa3f71284602 with persona

When choosing "ask as question" from the dropdown it doesn't change the submit button , although it actually seems to work. It's just not clear you have selected it before submitting.

steps to reproduce:

1. Start a new topic
2. Choose fro the dropdown next to "submit" and choose "ask as question"
3. Nothing happens (Although when pressing submit, the topic is asked as a question)

It's also not obvious this option is available I think too - so people miss it. I wanted to force "ask a question" for a specific category, but that is not currently possible due to it making "new topic" unusable on mobile - #42 

many thanks.

**Comment by joolswills** [comment]
(updated post with more info)

**Comment by NormandoHall** [comment]
up

**Comment by psychobunny** [comment]
Added a checkbox in the latest version, see https://github.com/NodeBB/nodebb-plugin-question-and-answer/commit/69e9f38db4fd552dc12d2d703c37af942cea9cbb
