### ISSUE TITLE
SEO: Possibility to add Solved tag directly in post title

### ISSUE THREAD

**Issue by digitalLumberjack** [NodeBB/nodebb-plugin-question-and-answer#44]
Hi, we use this plugin on forum.recalbox.com and it's really usefull :)

The only 'issue' we have is that google do not index the tag of the topic, as it only indexes the topic-title content.

So when searching on a search engine, one cannot know if the topic is solved.

I know there are many customisation available in google search results, anyone knows if google could use a metadata to add a status to a post in its search result ?

The other way would be to add the "Solved" text directly in title, and let the css work it to look exactly the same as what we have now.

Any thoughts ?

**Comment by Antosik** [comment]
Related article - https://developers.google.com/search/docs/advanced/structured-data/qapage

**Comment by psychobunny** [comment]
I actually have a working implementation of this elsewhere, will try and backport it to this plugin

**Comment by psychobunny** [comment]
available as of 0.11.0 👍

**Comment by psychobunny** [comment]
ex. https://search.google.com/test/rich-results?view=search-preview&id=ZvlvR-OGgWdGrIZrQKWYug
