### ISSUE TITLE
Failed to lookup view "admin/plugins/question-and-answer" in views directory "/usr/src/app/build/public/templates"

### ISSUE THREAD

**Issue by raphaelyancey** [NodeBB/nodebb-plugin-question-and-answer#46]
... when trying to access Q&A admin page.

> 1/12 11:24:53 [23] - error: /assets/templates/admin/plugins/question-and-answer.js
>  Error: ENOENT: no such file or directory, open '/usr/src/app/build/public/templates/admin/plugins/question-and-answer.tpl'

I run a dockerized **NodeBB 1.7.0**

Any idea why the files aren't created? Is there a plugin installation log I can look up?

**Comment by psychobunny** [comment]
This is probably fixed in the latest version, please comment if not
