### ISSUE TITLE
Topic creator/owner cannot "Mark this post as the correct answer"

### ISSUE THREAD

**Issue by rgigante** [NodeBB/nodebb-plugin-question-and-answer#49]
A standard (non-admin / non-moderator) user doesn't see in the post menu the "Mark this post as the correct answer". This option in instead only available on his own posts thus reducing the effectiveness of the Q&A functionality. Only moderators or admin see the "Mark this post as the correct answer" on any post.

"Mark this post as correct answer" doesn't show up for user KnickKnack attempting to mark r_gigante's post
<img width="763" alt="image" src="https://user-images.githubusercontent.com/13330358/49091555-64662c80-f260-11e8-99e7-fe158857b5ff.png">

"Mark this post as correct answer"  shows up for user KnickKnack attempting to mark his own post
<img width="754" alt="image" src="https://user-images.githubusercontent.com/13330358/49091572-6e882b00-f260-11e8-942f-35e186ce938c.png">

The issue currently is only appearing on 1.9.3, updating on 1.10.2 seems to restore the expected functionality

**Comment by psychobunny** [comment]
Confirmed that this is at least now working on latest, though I can't seem to find the commit in this repo so it might have been due to a nodebb bug sometime between 1.9.3-1.10.2
