### ISSUE TITLE
Why not change Submit button to Ask as Question?

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/nodebb-plugin-question-and-answer#54]
Using nodeBB: 1.12.1, nodejs 11.x, Plugin: 0.4.0, theme, Persona latest

Thank you

**Comment by NormandoHall** [comment]
bump

**Comment by NormandoHall** [comment]
It is important thing. When click "Ask a question" change the "Submit" button to "Ask a question"

**Comment by psychobunny** [comment]
Changed it to a checkbox-style option :+1:
