### ISSUE TITLE
Solved / Unsolved badges not displaying properly...

### ISSUE THREAD

**Issue by winterhalder** [NodeBB/nodebb-plugin-question-and-answer#59]
Hi - I recently upgraded to plugin 0.5.0 on NodeBB 1.12.2 - and instead of see [Unsolved] and [Solved] boxes in the lists, I see [[QANDA:TOPIC_SOLVED]] and [[QANDA:TOPIC_UNSOLVED]]. The funny thing is that the proper display "flashes" for a second - and is then replaced with this invalid display.

Is there a fix for this?

![2019-12-12_16-44-39](https://user-images.githubusercontent.com/3590310/70751815-43536b00-1cff-11ea-880f-7edbce327242.png)

**Comment by psychobunny** [comment]
should be fixed here: https://github.com/NodeBB/nodebb-plugin-question-and-answer/commit/fc204be1d8f80847a2dc709164681faf636b2037

**Comment by winterhalder** [comment]
Hmm, well, I believe I would have already had that fix? (that's from last August, right?).

In any event, I did I think end up finding my problem - it was a conflict with another plug-in (or at least, removing the other plug-in fixed it). I think it was nodebb-plugin-rainbows ?

**Comment by winterhalder** [comment]
Hmm, though maybe... it *does* look like I currently have 0.6.5 installed...  how I wouldn't have had the latest at that time I don't know...

**Comment by psychobunny** [comment]
The original post had you at 0.5.0 which is before that fix actually. In any case the latest works, glad you figured it out as well :)
