### ISSUE TITLE
Solved/unsolved tag does not appear in topic listing

### ISSUE THREAD

**Issue by gramakri** [NodeBB/nodebb-plugin-question-and-answer#70]
I am running the latest plugin 1.8.5 and we also updated today morning to NodeBB 1.6.0. The "Solved" tag appears correctly when visiting the actual topic. For example, https://forum.cloudron.io/topic/4009/grant-ftp-access-to-a-single-app-to-a-simple-user

![image](https://user-images.githubusercontent.com/82041/102665569-e8d2c300-4139-11eb-98fe-1c04796aff2d.png)

But it doesn't appear in the category topic listing.

![image](https://user-images.githubusercontent.com/82041/102665613-fd16c000-4139-11eb-8ba1-6823db54fbf1.png)

Is this change intentional or some bug (either the plugin or nodebb or cloudron package)?

**Comment by psychobunny** [comment]
Hi @gramakri, it seems fine here: https://community.nodebb.org/category/17/plugin-development

(We are running the plugin@0.8.5 and latest NodeBB@1.6.0)

**Comment by barisusakli** [comment]
@gramakri are you using latest persona theme?

**Comment by psychobunny** [comment]
^ yes sorry, the latest Q&A plugin does require the latest persona theme which was deployed after 1.16.0, sorry about that.

**Comment by gramakri** [comment]
@barisusakli @psychobunny yes, persona theme. Le me update the theme to 10.3.12

**Comment by gramakri** [comment]
Thanks, updating the theme made it all work!
