### ISSUE TITLE
Removing tags a post removes the Unsolved header

### ISSUE THREAD

**Issue by gramakri** [NodeBB/nodebb-plugin-question-and-answer#77]
I am running NodeBB 1.6.2 and with the latest plugin.

Steps to reproduce:
* Have an existing post tagged as say "wip".
* Mark the post as solved. The solved label appears in the post/
* Remove the "wip" tag.
* The solved label also disappears.

Is this expected behavior? maybe this plugin is internally using tags but editing tags ends up removing the internal solved label as well.

**Comment by barisusakli** [comment]
I think this might already be fixed on latest master, I can't reproduce it. Removing a tag doesn't remove the solved/unsolved status.

**Comment by gramakri** [comment]
@barisusakli are you referring to NodeBB master? If so, I can close this then and wait for NodeBB 1.6.3 or 1.7.0. Thanks

**Comment by barisusakli** [comment]
Yeah was referring to latest master(which will be 1.17.0) and the latest version of this plugin (0.8.7)

**Comment by gramakri** [comment]
@barisusakli thanks, I will close this and re-open later if it's in the next release.
