### ISSUE TITLE
Q&A Label not visible in Slick Theme

### ISSUE THREAD

**Issue by rgigante** [NodeBB/nodebb-plugin-question-and-answer#79]
Hi, thanks for the great plugin.

We used the Q&A plugin since a while and it worked nicely on the _Persona Theme_ with  labels being properly visible inside categories. Now we've switched to _Slick Theme_ and the Q&A labels are gone. How it's possible to show 'em within the Slick Theme?

**Comment by barisusakli** [comment]
seems to work
![image](https://user-images.githubusercontent.com/2583394/132896894-4183f639-98d8-47a4-9227-ac8fae4b8b01.png)

**Comment by barisusakli** [comment]
https://github.com/pichalite/nodebb-theme-slick/commit/a90b11dfeefb4e8cbf9e2267f505c17268baf30c
