### ISSUE TITLE
Stylesheet missing with NodeBB v2.5.3

### ISSUE THREAD

**Issue by nebulade** [NodeBB/nodebb-plugin-question-and-answer#93]
Hi there, after updating NodeBB to 2.5.3 both unresolved and resolved badges are missing their stylesheet:

![image](https://user-images.githubusercontent.com/646768/191240634-384743a2-9d61-4e18-803d-3215aeb51d24.png)

It appears that nothing is defining the `unanswered` and `answered` classes. There are also no errors shown in the webinspector nor while rebuilding nodebb. How could I debug this further? It can be seen live at for example https://forum.cloudron.io/category/4/support

This is using the latest plugin version 1.0.0 also

**Comment by barisusakli** [comment]
Which version of question and answer plugin?

**Comment by barisusakli** [comment]
1.0.0 is only compatible with upcoming nodebb 3.0, install 0.12.25 and it should work.

**Comment by nebulade** [comment]
Ah that explains it then. I have uninstalled v1.0.0 now and installed the other version and it works again now. Not sure why nodebb installed v1.0 then in the first place.

**Comment by nebulade** [comment]
The package.json now contains `"nodebb-plugin-question-and-answer": "0.12.25",` but I am not sure what it was before I did the reinstall of it. One possible issue could have been that we use `yarn` instead of `npm` currently which had side-effects in the past. See https://github.com/NodeBB/NodeBB/issues/10877 for this. Will keep this updated once I find out more.
