### ISSUE TITLE
can you move "solution" label to language files

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-plugin-question-and-answer#94]
"solution" label is not available for translation. 

<img width="497" alt="Screen Shot 2022-10-28 at 17 28 59" src="https://user-images.githubusercontent.com/52054408/198736026-ddcdcc08-95eb-4063-83b2-264587563554.png">

**Comment by barisusakli** [comment]
Isn't it already in language files? https://github.com/NodeBB/nodebb-plugin-question-and-answer/commit/9dd4eda58cdc4aee9aedd4f58dad2822ef4daa03

**Comment by barisusakli** [comment]
Feel free to pr to add it to tr files https://github.com/NodeBB/nodebb-plugin-question-and-answer/blob/master/static/languages/tr/qanda.json

**Comment by AliCihan** [comment]
https://github.com/NodeBB/nodebb-plugin-question-and-answer/pull/95
