### ISSUE TITLE
[BUG] Cannot save option in plugin page

### ISSUE THREAD

**Issue by MaxWaldorf** [NodeBB/nodebb-plugin-question-and-answer#97]
Hello,

I am using NodeBB v2.8.6 and there is no save option in the plugin configuration page to save changes...
I guess the plugin needs a slight update to match NodeBB changes?

Thank you

**Comment by barisusakli** [comment]
Which version of the plugin are you using? On nodebb 2.x you should use [0.12.29]

**Comment by MaxWaldorf** [comment]
It says: 1.0.14

how should I call this specific version on npm?

**Comment by barisusakli** [comment]
You can install with cli like `npm i nodebb-plugin-question-and-answer@0.12.29`

**Comment by MaxWaldorf** [comment]
thx it works.

Should I assume the v1 is for a later version of nodeBB?

**Comment by barisusakli** [comment]
Yes, it is for nodebb 3.x which isn't released yet.
